### ISSUE TITLE
Ambiguity around Zookeeper implementation could cause red flags

### ISSUE THREAD

**Issue by JasonvanBrackel** [apprenda/acp-reference-architecture#3]
On the topology page around coordination nodes we say

> The servers run a custom implementation of Apache ZooKeeper, running as a Windows service.

We should specifically spell out that it's not our fork and is a community supported fork.  Not doing so can raise questions around unknown risk.

**Comment by mammerman** [comment]
resolved https://github.com/apprenda/acp-reference-architecture/commit/958f9923d15790f3af7b56474c58e08668eba233
