### ISSUE TITLE
Add addtional note on deployment policies for Federation Nodes as App Nodes

### ISSUE THREAD

**Issue by JasonvanBrackel** [apprenda/acp-reference-architecture#5]
While we say that Federation Nodes become app nodes, we should point out that application workloads can be prevented from deploying there.  Especially in architectural areas where the ADFS server are in a DMZ or some other network topology that separates them from the whole.

**Comment by mammerman** [comment]
Resolved: https://github.com/apprenda/acp-reference-architecture/commit/09d6a4a5026183f8e2d3cf2625208942a2a6e19e
